/**
 * Audio Analyser Service
 *
 * Multi-source AI detection:
 * 1. GitHub AI blocklist (1600+ confirmed Spotify artist IDs)
 * 2. Wikipedia — confirms real artists AND detects AI confirmation
 * 3. MusicBrainz — comprehensive music database
 * 4. Last.fm — listener counts and tags
 * 5. Discogs — physical release history (unbeatable human proof)
 * 6. Genius — songwriter credits and verified artist pages
 * 7. Spotify audio features — production signal analysis
 */

const axios = require('axios');

const AI_NAME_SIGNALS = [
  'suno', 'udio', 'musicgen', 'aiva', 'mubert', 'soundraw', 'boomy',
  'beatoven', 'loudly', 'riffusion', 'harmonai', 'splash music',
  'obscurest vinyl', 'untraceable records', 'banned vinyl', 'brainrot',
  'ai generated', 'artificial intelligence music', 'stable audio', 'musiclm'
];

const AI_WIKI_SIGNALS = [
  'ai-generated', 'ai generated', 'artificial intelligence', 'generated by ai',
  'likely being ai', 'suspected ai', 'suno', 'udio', 'generative ai',
  'ai music', 'machine learning', 'ai-created', 'chatgpt', 'ai artist'
];

const MUSIC_KEYWORDS = [
  'singer', 'rapper', 'musician', 'artist', 'band', 'dj', 'producer',
  'songwriter', 'vocalist', 'composer', 'discography', 'album', 'record',
  'hip hop', 'r&b', 'pop', 'jazz', 'soul', 'reggae', 'afrobeats', 'amapiano',
  'gospel', 'blues', 'rock', 'electronic', 'dancehall', 'music group',
  'recording artist', 'south african', 'nigerian', 'ghanaian', 'kenyan'
];

const verificationCache = new Map();
let aiBlocklist       = new Set();
let blocklistLoaded   = false;
let blocklistLoadTime = 0;

// ── GitHub AI blocklist ──────────────────────────────────────────────────
async function loadAiBlocklist() {
  const now = Date.now();
  if (blocklistLoaded && (now - blocklistLoadTime) < 24 * 60 * 60 * 1000) return;
  try {
    const url = 'https://raw.githubusercontent.com/eye-wave/spotify-ai-blocklist/main/ai-list.txt';
    const res = await axios.get(url, { timeout: 10000 });
    if (res.status === 200 && res.data) {
      const ids = res.data.split('\n')
        .map(l => l.trim())
        .filter(l => l.includes('spotify.com/artist/'))
        .map(l => l.split('spotify.com/artist/')[1]?.split('?')[0])
        .filter(Boolean);
      aiBlocklist       = new Set(ids);
      blocklistLoaded   = true;
      blocklistLoadTime = now;
      console.log(`AI blocklist loaded: ${aiBlocklist.size} artist IDs`);
    }
  } catch (err) {
    console.warn('Could not load AI blocklist:', err.message);
  }
}
loadAiBlocklist();

// ── Wikipedia ─────────────────────────────────────────────────────────────
async function checkWikipedia(artistName) {
  try {
    const url = `https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(artistName)}`;
    const res = await axios.get(url, { timeout: 4000 });
    if (res.status === 200 && res.data) {
      const text = ((res.data.extract || '') + ' ' + (res.data.description || '')).toLowerCase();
      const isAiConfirmed = AI_WIKI_SIGNALS.some(sig => text.includes(sig));
      const isMusicArtist = MUSIC_KEYWORDS.some(kw => text.includes(kw));
      return { found: true, isAiConfirmed, isMusicArtist };
    }
  } catch (err) {
    if (err.response?.status === 404) return { found: false, isAiConfirmed: false, isMusicArtist: false };
  }
  return null;
}

// ── MusicBrainz ───────────────────────────────────────────────────────────
async function checkMusicBrainz(artistName) {
  try {
    const url = `https://musicbrainz.org/ws/2/artist/?query=artist:${encodeURIComponent(artistName)}&limit=1&fmt=json`;
    const res = await axios.get(url, {
      timeout: 5000,
      headers: { 'User-Agent': 'Provenance/1.0 (provenance-trace.netlify.app)' }
    });
    if (res.status === 200 && res.data?.artists?.length > 0) {
      const artist = res.data.artists[0];
      if ((artist.score || 0) >= 80) return { found: true, name: artist.name, score: artist.score };
    }
    return { found: false };
  } catch (err) {
    return null;
  }
}

// ── Last.fm ───────────────────────────────────────────────────────────────
async function checkLastFm(artistName) {
  const apiKey = process.env.LASTFM_API_KEY;
  if (!apiKey) return null;
  try {
    const url = `https://ws.audioscrobbler.com/2.0/?method=artist.getinfo&artist=${encodeURIComponent(artistName)}&api_key=${apiKey}&format=json`;
    const res = await axios.get(url, { timeout: 4000 });
    if (res.status === 200 && res.data?.artist) {
      const listeners = parseInt(res.data.artist.stats?.listeners || '0');
      return { found: true, listeners, isEstablished: listeners > 1000 };
    }
    return { found: false };
  } catch (err) {
    return null;
  }
}

// ── Discogs — physical release history (unbeatable human proof) ──────────
async function checkDiscogs(artistName) {
  const token = process.env.DISCOGS_TOKEN;
  if (!token) return null;
  try {
    const url = `https://api.discogs.com/database/search?q=${encodeURIComponent(artistName)}&type=artist&token=${token}`;
    const res = await axios.get(url, {
      timeout: 5000,
      headers: { 'User-Agent': 'Provenance/1.0' }
    });
    if (res.status === 200 && res.data?.results?.length > 0) {
      // Discogs only catalogues real physical/digital releases — no AI artist would appear here
      const match = res.data.results.find(r =>
        r.title?.toLowerCase().includes(artistName.toLowerCase())
      );
      if (match) return { found: true, name: match.title };
    }
    return { found: false };
  } catch (err) {
    return null;
  }
}

// ── Genius — songwriter credits and verified artist pages ─────────────────
async function checkGenius(artistName) {
  const token = process.env.GENIUS_TOKEN;
  if (!token) return null;
  try {
    const url = `https://api.genius.com/search?q=${encodeURIComponent(artistName)}`;
    const res = await axios.get(url, {
      timeout: 5000,
      headers: { 'Authorization': `Bearer ${token}` }
    });
    if (res.status === 200 && res.data?.response?.hits?.length > 0) {
      const hit = res.data.response.hits.find(h =>
        h.result?.primary_artist?.name?.toLowerCase().includes(artistName.toLowerCase()) ||
        artistName.toLowerCase().includes(h.result?.primary_artist?.name?.toLowerCase() || '')
      );
      if (hit) {
        return {
          found: true,
          name: hit.result.primary_artist.name,
          isVerified: hit.result.primary_artist.is_verified || false
        };
      }
    }
    return { found: false };
  } catch (err) {
    return null;
  }
}

// ── Combined artist verification ────────────────────────────────────────
async function verifyArtist(artistName, spotifyArtistId) {
  if (!artistName) return { isHuman: false, isAi: false, confidence: 0, sources: [] };

  const cacheKey = (spotifyArtistId || artistName).toLowerCase().trim();
  if (verificationCache.has(cacheKey)) return verificationCache.get(cacheKey);

  if (spotifyArtistId && aiBlocklist.has(spotifyArtistId)) {
    const result = { isHuman: false, isAi: true, confidence: 0.95, sources: ['github-blocklist'] };
    verificationCache.set(cacheKey, result);
    console.log(`Blocklist match: ${artistName} (${spotifyArtistId})`);
    return result;
  }

  const [wiki, musicbrainz, lastfm, discogs, genius] = await Promise.all([
    checkWikipedia(artistName),
    checkMusicBrainz(artistName),
    checkLastFm(artistName),
    checkDiscogs(artistName),
    checkGenius(artistName)
  ]);

  if (wiki?.isAiConfirmed) {
    const result = { isHuman: false, isAi: true, confidence: 0.90, sources: ['wikipedia-ai-confirmed'] };
    verificationCache.set(cacheKey, result);
    console.log(`Wikipedia confirms AI: ${artistName}`);
    return result;
  }

  const sources    = [];
  let humanSignals = 0;
  let totalSources = 0;

  if (wiki !== null) {
    totalSources++;
    if (wiki.found && wiki.isMusicArtist) { humanSignals++; sources.push('wikipedia'); }
  }
  if (musicbrainz !== null) {
    totalSources++;
    if (musicbrainz.found) { humanSignals += 2; sources.push('musicbrainz'); }
  }
  if (lastfm !== null) {
    totalSources++;
    if (lastfm.found && lastfm.isEstablished) { humanSignals++; sources.push('lastfm'); }
    else if (lastfm.found && lastfm.listeners > 0) { humanSignals += 0.5; sources.push('lastfm-low'); }
  }
  if (discogs !== null) {
    totalSources++;
    if (discogs.found) { humanSignals += 1.5; sources.push('discogs'); } // Physical releases = strong signal
  }
  if (genius !== null) {
    totalSources++;
    if (genius.found) {
      humanSignals += genius.isVerified ? 1.5 : 0.75;
      sources.push(genius.isVerified ? 'genius-verified' : 'genius');
    }
  }

  let isHuman = false, confidence = 0;
  if (humanSignals >= 2)      { isHuman = true; confidence = Math.min(0.95, 0.60 + humanSignals * 0.08); }
  else if (humanSignals >= 1) { isHuman = true; confidence = 0.65; }
  else if (totalSources >= 3 && humanSignals === 0) { confidence = 0.55; }

  const result = { isHuman, isAi: false, confidence, sources, humanSignals, totalSources };
  verificationCache.set(cacheKey, result);
  console.log(`Artist verification [${artistName}]: human=${isHuman}, signals=${humanSignals}, sources=[${sources.join(',')}]`);
  return result;
}

// ── Main analyse function ───────────────────────────────────────────────
async function analyse(resolved, songData) {
  // Step 1: Fast checks first — blocklist, explicit signals, verification waterfall
  const fastResult = await analyseFromSpotifyFeatures(songData);

  // If the fast path is already confident (clearly AI or clearly human), use it
  const isConfident = fastResult.aiLikelihoodScore >= 0.75 || fastResult.aiLikelihoodScore <= 0.20;

  if (isConfident) {
    return fastResult;
  }

  // Step 2: Uncertain case — ask Claude (with web search) + Google Search
  // whether this is a known AI artist or a confirmed voice clone of a real artist.
  // This is faster and often more accurate than the audio waterfall for
  // catching cases that are already publicly documented (e.g. L$30 cloning MJ).
  try {
    const [claudeCheck, googleCheck] = await Promise.all([
      checkClaudeVerification(songData.artist, songData.title),
      checkGoogleSearch(songData.artist)
    ]);

    if (claudeCheck && claudeCheck.sourceFound && claudeCheck.confidence >= 0.6) {
      if (claudeCheck.isVoiceClone && claudeCheck.clonedArtistName) {
        return buildResult({
          aiScore: Math.max(0.80, claudeCheck.confidence),
          pitchCorrection: 'High', breathPresence: 'Low',
          timingRegularity: 'Very High', spectralSmoothing: 'High',
          dynamicRange: 'Compressed',
          confidence: claudeCheck.confidence,
          method: 'claude-web-verified-voice-clone',
          confirmedClonedArtist: claudeCheck.clonedArtistName,
          verificationSummary: claudeCheck.summary
        });
      }
      if (claudeCheck.isAiArtist) {
        return buildResult({
          aiScore: Math.max(0.80, claudeCheck.confidence),
          pitchCorrection: 'High', breathPresence: 'Low',
          timingRegularity: 'Very High', spectralSmoothing: 'High',
          dynamicRange: 'Compressed',
          confidence: claudeCheck.confidence,
          method: 'claude-web-verified-ai-artist',
          verificationSummary: claudeCheck.summary
        });
      }
    }

    if (googleCheck?.found && googleCheck.aiKeywordHit) {
      // Corroborating signal even without Claude's confirmation
      const boosted = Math.min(0.85, fastResult.aiLikelihoodScore + 0.25);
      return { ...fastResult, aiLikelihoodScore: boosted, method: fastResult.method + '+google-search-signal' };
    }
  } catch (err) {
    console.warn('Claude/Google verification step failed:', err.message);
  }

  // Step 3: Still uncertain — try slow audio analysis to catch voice cloning etc.
  if (process.env.PYTHON_SERVICE_URL) {
    try {
      const audioResult = await callPythonService(resolved, songData);
      if (audioResult && audioResult.method !== 'metadata-heuristics') return audioResult;
    } catch (err) {
      console.warn('Python audio service unavailable, using fast-path result');
    }
  }

  return fastResult;
}

async function callPythonService(resolved, songData) {
  const payload = {
    input_type:   resolved.type,
    url:          resolved.originalUrl || null,
    song_title:   songData.title,
    artist:       songData.artist,
    search_query: `${songData.artist} ${songData.title}`
  };
  const response = await axios.post(
    `${process.env.PYTHON_SERVICE_URL}/analyse`,
    payload,
    { timeout: 30000 }
  );
  return response.data;
}

async function analyseFromSpotifyFeatures(songData) {
  const af             = songData.audioFeatures;
  const artist         = (songData.artist || '').toLowerCase();
  const title          = (songData.title  || '').toLowerCase();
  const genres         = (songData.genres || []).map(g => g.toLowerCase());
  const spotifyArtistId = songData.artistId || null;

  const isExplicitlyAi = songData.isAiGenerated ||
    AI_NAME_SIGNALS.some(sig => artist.includes(sig) || title.includes(sig));

  if (isExplicitlyAi) {
    return buildResult({
      aiScore: 0.88, pitchCorrection: 'High', breathPresence: 'Low',
      timingRegularity: 'Very High', spectralSmoothing: 'High',
      dynamicRange: 'Compressed', confidence: 0.90, method: 'explicit-ai-signal'
    });
  }

  const verification = await verifyArtist(songData.artist, spotifyArtistId);

  if (verification.isAi) {
    return buildResult({
      aiScore: 0.88, pitchCorrection: 'High', breathPresence: 'Low',
      timingRegularity: 'Very High', spectralSmoothing: 'High',
      dynamicRange: 'Compressed', confidence: verification.confidence,
      method: `ai-confirmed(${verification.sources.join('+')})`
    });
  }

  if (verification.isHuman && verification.confidence >= 0.65) {
    const baseScore = 0.10;
    if (af) return analyseWithFeatures(af, genres, baseScore, verification);
    return buildResult({
      aiScore: baseScore, pitchCorrection: 'Low', breathPresence: 'High',
      timingRegularity: 'Moderate', spectralSmoothing: 'Low', dynamicRange: 'Wide',
      confidence: verification.confidence,
      method: `verified-human(${verification.sources.join('+')})`
    });
  }

  if (!verification.isHuman && verification.totalSources >= 3) {
    const baseScore = 0.55;
    if (af) return analyseWithFeatures(af, genres, baseScore, verification);
    return analyseFromGenre(genres, baseScore);
  }

  if (af) return analyseWithFeatures(af, genres, 0.35, verification);
  return analyseFromGenre(genres, 0.35);
}

function analyseWithFeatures(af, genres, baseScore, verification) {
  let aiScore = baseScore;

  if (af.liveness < 0.08)          aiScore += 0.15;
  else if (af.liveness < 0.15)     aiScore += 0.07;
  else                              aiScore -= 0.10;

  if (af.acousticness < 0.05)      aiScore += 0.10;
  else if (af.acousticness > 0.50) aiScore -= 0.15;

  if (af.energy > 0.75 && af.acousticness < 0.10) aiScore += 0.06;

  if (af.speechiness > 0.15)       aiScore -= 0.10;
  else if (af.speechiness < 0.03)  aiScore += 0.04;

  if (af.loudness > -3)             aiScore += 0.06;
  else if (af.loudness < -12)       aiScore -= 0.04;

  if (isGenre(genres, ['amapiano', 'afrohouse', 'kwaito', 'afrobeats', 'afropop',
                        'dancehall', 'reggae', 'latin', 'soca', 'highlife',
                        'r&b', 'soul', 'gospel', 'jazz', 'blues', 'folk',
                        'acoustic', 'classical', 'neo soul', 'trap soul',
                        'gengetone', 'bongo flava', 'afrosoul', 'grime'])) {
    aiScore -= 0.18;
  }

  aiScore = Math.max(0, Math.min(1, aiScore));

  const pitchCorrection  = af.energy > 0.7 && af.acousticness < 0.2 ? 'High' : af.acousticness > 0.5 ? 'Low' : 'Moderate';
  const breathPresence   = af.liveness > 0.2 ? 'High' : af.liveness > 0.1 ? 'Moderate' : 'Low';
  const timingRegularity = af.danceability > 0.8 ? 'Very High' : af.danceability > 0.6 ? 'High' : 'Moderate';
  const spectralSmoothing= af.acousticness < 0.1 ? 'High' : af.acousticness > 0.4 ? 'Low' : 'Moderate';
  const dynamicRange     = af.loudness > -5 ? 'Compressed' : af.loudness > -10 ? 'Moderate' : 'Wide';

  const sources = verification?.sources?.join('+') || 'none';
  return buildResult({
    aiScore, pitchCorrection, breathPresence, timingRegularity,
    spectralSmoothing, dynamicRange,
    confidence: Math.max(0.65, verification?.confidence || 0.65),
    method: `verified(${sources})+spotify-features`
  });
}

// ── Claude API + Google Search verification ─────────────────────────────
// For uncertain cases, ask Claude (with web search) whether the artist
// is a known AI-generated artist or a voice clone of a real artist.
// This catches cases like L$30 using a cloned Michael Jackson voice,
// where verification sources alone can't tell.

const claudeVerificationCache = new Map();

async function checkClaudeVerification(artistName, songTitle) {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey || !artistName) return null;

  const cacheKey = `${artistName}::${songTitle}`.toLowerCase().trim();
  if (claudeVerificationCache.has(cacheKey)) return claudeVerificationCache.get(cacheKey);

  try {
    const prompt = `Search the web to answer this about a music artist/track.

Artist: "${artistName}"
Track: "${songTitle}"

Determine:
1. Is "${artistName}" a confirmed or widely-reported AI-generated artist (e.g. made with Suno, Udio, or similar)?
2. Does this artist or track use a cloned/AI-replicated voice of a real, named human artist? If so, who?
3. Is there any public reporting (news, Reddit, music blogs) discussing this specifically?

Respond with ONLY a JSON object, no other text, in this exact shape:
{"isAiArtist": true/false, "isVoiceClone": true/false, "clonedArtistName": "Name or null", "confidence": 0.0-1.0, "summary": "one short sentence", "sourceFound": true/false}`;

    const response = await axios.post(
      'https://api.anthropic.com/v1/messages',
      {
        model: 'claude-haiku-4-5-20251001',
        max_tokens: 500,
        messages: [{ role: 'user', content: prompt }],
        tools: [{ type: 'web_search_20250305', name: 'web_search' }]
      },
      {
        headers: {
          'Content-Type': 'application/json',
          'x-api-key': apiKey,
          'anthropic-version': '2023-06-01'
        },
        timeout: 20000
      }
    );

    // Extract text content from response (may include tool use blocks)
    const textBlocks = (response.data?.content || []).filter(b => b.type === 'text');
    const fullText = textBlocks.map(b => b.text).join('\n');

    // Try to find a JSON object in the response
    const jsonMatch = fullText.match(/\{[^{}]*"isAiArtist"[^{}]*\}/s) || fullText.match(/\{.*\}/s);
    if (!jsonMatch) return null;

    const parsed = JSON.parse(jsonMatch[0]);
    claudeVerificationCache.set(cacheKey, parsed);
    console.log(`Claude verification [${artistName}]:`, JSON.stringify(parsed));
    return parsed;

  } catch (err) {
    console.warn('Claude verification failed:', err.message);
    return null;
  }
}

// ── Google Custom Search backup check ────────────────────────────────────
async function checkGoogleSearch(artistName) {
  const apiKey = process.env.GOOGLE_SEARCH_API_KEY;
  const engineId = process.env.GOOGLE_SEARCH_ENGINE_ID;
  if (!apiKey || !engineId || !artistName) return null;

  try {
    const query = `"${artistName}" AI generated artist OR AI voice clone OR Suno OR Udio`;
    const url = `https://www.googleapis.com/customsearch/v1?key=${apiKey}&cx=${engineId}&q=${encodeURIComponent(query)}&num=5`;
    const res = await axios.get(url, { timeout: 6000 });

    if (res.status === 200 && res.data?.items?.length > 0) {
      const snippets = res.data.items.map(item => (item.snippet || '').toLowerCase()).join(' ');
      const aiKeywordHit = ['ai-generated', 'ai generated', 'voice clone', 'suno', 'udio', 'artificial intelligence']
        .some(kw => snippets.includes(kw));
      return { found: true, aiKeywordHit, resultCount: res.data.items.length };
    }
    return { found: false };
  } catch (err) {
    console.warn('Google Search check failed:', err.message);
    return null;
  }
}


  let aiScore = baseScore;
  if (isGenre(genres, ['amapiano', 'afrobeats', 'afropop', 'afrohouse', 'kwaito',
                        'dancehall', 'reggae', 'latin', 'soca', 'highlife',
                        'r&b', 'soul', 'gospel', 'jazz', 'blues', 'folk',
                        'acoustic', 'classical', 'neo soul', 'trap soul',
                        'gengetone', 'bongo flava', 'afrosoul'])) {
    aiScore = Math.min(aiScore, 0.20);
  }
  if (isGenre(genres, ['edm', 'electronic', 'synth', 'ambient'])) {
    aiScore = Math.max(aiScore, 0.35);
  }
  return buildResult({
    aiScore, pitchCorrection: 'Low-Moderate', breathPresence: 'Moderate',
    timingRegularity: 'Moderate', spectralSmoothing: 'Low-Moderate',
    dynamicRange: 'Moderate', confidence: 0.35, method: 'genre-heuristics'
  });
}

function buildResult({ aiScore, pitchCorrection, breathPresence, timingRegularity, spectralSmoothing, dynamicRange, confidence, method, confirmedClonedArtist, verificationSummary }) {
  return {
    pitchCorrection, breathPresence, timingRegularity, spectralSmoothing, dynamicRange,
    aiLikelihoodScore: aiScore,
    modelConfidence:   confidence,
    signalConfidence:  confidence * 0.95,
    method,
    confirmedClonedArtist: confirmedClonedArtist || null,
    verificationSummary: verificationSummary || null
  };
}

function isGenre(genres, targets) {
  return targets.some(t => genres.some(g => g.includes(t)));
}

module.exports = { analyse };
